trigger:
- master

pool:
  vmImage: 'windows-latest'

name: $(Build.Reason)_commit-$(Build.SourceVersion)_$(Date:yyyyMMdd_HHmmss)

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@1
  
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: PowerShell@2
    displayName: Update Project File
    inputs:
      filePath: '$(SYSTEM.DEFAULTWORKINGDIRECTORY)\Build\UpdateProjectFile.ps1'
      arguments: '-PathToCsprojFile $(SYSTEM.DEFAULTWORKINGDIRECTORY)\BricklinkSharp.Client\BricklinkSharp.Client.csproj -BuildId $(BUILD.BUILDID)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      
  - task: CopyFiles@2
    inputs:
        SourceFolder: '$(SYSTEM.DEFAULTWORKINGDIRECTORY)'
        Contents: BricklinkSharp.Client\bin\$(BuildConfiguration)\**
        TargetFolder: '$(BUILD.ARTIFACTSTAGINGDIRECTORY)'

  - task: PublishBuildArtifacts@1
    inputs:
        PathtoPublish: '$(BUILD.ARTIFACTSTAGINGDIRECTORY)'
        ArtifactName: 'drop'
        publishLocation: 'Container'