trigger:
- master

pool:
  vmImage: 'windows-latest'

name: $(Build.Build.Reason)_commit-$(Build.SourceVersion)_$(Date:yyyyMMdd_HHmmss)

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@1
  
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: PowerShell@2
    displayName: Update Project File
    inputs:
      filePath: '$(system.defaultworkingdirectory)\Build\UpdateProjectFile.ps1'
      arguments: '-PathToCsprojFile $(system.defaultworkingdirectory)\BricklinkSharp.Client\BricklinkSharp.Client.csproj -BuildId $(Build.BuildId)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'